FROM python:3.10-slim

WORKDIR /app

RUN apt-get update && apt-get install -y wget unzip

RUN wget -q https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb \
    && apt-get install -y ./google-chrome-stable_current_amd64.deb \
    && rm google-chrome-stable_current_amd64.deb

COPY requirements.txt .
COPY test_gamehub.py .

RUN pip install --no-cache-dir -r requirements.txt

CMD ["pytest", "test_gamehub.py", "-v"]
